[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "specmangle"
dynamic = ["version"]
description = "Photometry-based 'mangling' (calibration) of astronomical spectra"
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    {name = "Caden Gobat", email = "cgobat@sdsu.edu"},
]
requires-python = ">=3.10"
dependencies = [
    "astropy",
    "astroquery",
    "numpy",
    "scipy",
    "specutils",
]

[project.optional-dependencies]
test = ["pytest"]
docs = [
    "sphinx-astropy[confv3]>=1.11",
    "sphinx-design",
]

[project.urls]
Documentation = "https://cgobat.github.io/specmangle/"
Repository = "https://github.com/cgobat/specmangle"

[tool.setuptools]
package-dir = {specmangle = "src"}

[tool.setuptools.dynamic]
version = {attr = "specmangle.__version__"}

[tool.pytest.ini_options]
testpaths = ["tests"]
